version: "0.1.0"

index:
  name: doc_idx
  prefix: doc_idx
  storage_type: hash

fields:
  - name: embedding
    type: vector
    attrs:
      dims: 768
      algorithm: hnsw
      distance_metric: cosine
      datatype: float32
  - name: text
    type: text

  - name: source
    type: tag

  - name: language
    type: tag

  - name: content_type
    type: tag

  - name: page_number
    type: numeric
  
  ###v2
  - name: pages
    type: tag

  - name: page_span
    type: tag
  ####
  - name: chunk_index
    type: numeric

  - name: total_chunks
    type: numeric

  - name: timestamp
    type: numeric

  - name: content_length
    type: numeric

  - name: parent_id
    type: tag